global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
route:
  receiver: mattermost-alertmananger
  group_by:
  - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 120m
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
    #- dev
  - instance
templates: []
receivers:
- name: 'mattermost-alertmananger'
  webhook_configs:
  - send_resolved: true
    url: 'https://chat.skyroom.online/plugins/com.cpanato.alertmanager/api/webhook?token=vz2_DsE4wvqii9TM//U9-WtBiiI2B9so'
    #url: 'https://chat.skyroom.online/plugins/com.cpanato.alertmanager/api/webhook?token=2KvbW8-trTDrDg_4fde5pcnFzwEi3xtY'
