global:
  evaluation_interval: 3s
  scrape_interval: 30s
  scrape_timeout: 2s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'devops monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  - '/etc/prometheus/rules/*.rules'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: internal
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/internal.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: production
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/production.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: media-v1
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/media-v1.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: media-v2
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/media-v2.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: licence
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/licence.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: stage
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/stage.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: k8s-stage
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/k8s-stage.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: mohit
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/mohit.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: data-team
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/data-team.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: record
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/record.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: test
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/test.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: 'pingexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.128.35:9427']

  - job_name: 'haproxy_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.128.35:9101']
      - targets: ['192.168.128.35:9102']
      - targets: ['192.168.128.35:9103']

  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['web1_nginx:9113']
      - targets: ['web2_nginx:9113']
      - targets: ['web3_nginx:9113']
      - targets: ['web4_nginx:9113']
      - targets: ['web5_nginx:9113']

  - job_name: 'nginxlog_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['31.7.69.24:4040']
        #      - targets: ['212.33.204.6:4040']
      - targets: ['212.33.204.21:4040']
      - targets: ['212.33.204.22:4040']
      - targets: ['212.33.204.23:4040']
      - targets: ['212.33.204.24:4040']
      - targets: ['212.33.204.25:4040']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prisma-read'
    scrape_interval: 5s
    metrics_path: /api/db/read/metrics
    static_configs:
      - targets: ['77.238.109.112:3000']
      - targets: ['212.33.204.51:3000']
      - targets: ['212.33.204.51:4000']
        labels:
          type: prisma-read
          group: vms

  - job_name: 'prisma-write'
    scrape_interval: 5s
    metrics_path: /api/db/write/metrics
    static_configs:
      - targets: ['77.238.109.112:3000']
      - targets: ['212.33.204.51:3000']
      - targets: ['212.33.204.51:4000']
        labels:
          type: prisma-write
          group: vms          

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
