global:
  evaluation_interval: 3s
  scrape_interval: 30s
  scrape_timeout: 2s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'devops monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  - '/etc/prometheus/rules/*.rules'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: Skyroom-Internal
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/internal.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: Skyroom-SRV
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/srv.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: Skyroom-Media
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/media.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'

  - job_name: Skyroom-Licence
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node/licence.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: ['__param_target']
        regex:         '(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9100'



  - job_name: 'pingexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.128.35:9427']

  - job_name: 'haproxy_exporter'
    scrape_interval: 5s
    static_configs:
            # - targets: ['192.168.128.35:9101']
      - targets: ['192.168.128.35:9102']
      - targets: ['192.168.128.35:9103']

  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
            #      - targets: ['192.168.128.35:9109']
            #      - targets: ['192.168.128.35:9110']
            #      - targets: ['192.168.128.35:9111']
            #      - targets: ['192.168.128.35:9112']
            #      - targets: ['192.168.128.35:9113']
      - targets: ['web1_nginx:9113']
      - targets: ['web2_nginx:9113']
      - targets: ['web3_nginx:9113']
      - targets: ['web4_nginx:9113']
      - targets: ['web5_nginx:9113']

  - job_name: 'nginxlog_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['31.7.69.24:4040']
        #      - targets: ['212.33.204.6:4040']
      - targets: ['212.33.204.21:4040']
      - targets: ['212.33.204.22:4040']
      - targets: ['212.33.204.23:4040']
      - targets: ['212.33.204.24:4040']
      - targets: ['212.33.204.25:4040']


#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

        # - job_name: 'postgres'
        # scrape_interval: 6s
        # scrape_timeout: 5s
        # static_configs:
        # - targets: ['db-master:90']
        # - targets: ['db-slave:80']
        # - job_name: 'pushgateway'
        # scrape_interval: 10s
        # honor_labels: true
        # static_configs:
        # - targets: ['pushgateway:9091']

        #  - job_name: node
        #    scrape_timeout: 5s
        #    scrape_interval: 5s
        #    file_sd_configs:
        #      - files:
        #        - /etc/prometheus/file_sd/node/*.yaml
    

#nginx status code 4xx
  - alert: 4xx nginx status codes are unusual
    expr: sum(rate(nginx_http_response_count_total{status =~ "4.*"}[1m])) by (status) > 120
    for: 35s
    labels:
      severity: critical
    annotations:
      summary: "4xx nginx status codes are unusual"
      description: " number of 4xx status codes: {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

#nginx status code 5xx
  - alert: 5xx nginx status codes are unusual
    expr: sum(rate(nginx_http_response_count_total{status =~ "5.*"}[1m])) by (status) > 17
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "5xx nginx status codes are unusual"
      description: " number of 5xx status codes: {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
